/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.model;

import org.junit.Test;


/**
 * Model tests for Author
 */
public class AuthorTest {
    private final Author model = new Author();

    /**
     * Model tests for Author
     */
    @Test
    public void testAuthor() {
        // TODO: test Author
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'affiliation'
     */
    @Test
    public void affiliationTest() {
        // TODO: test affiliation
    }

}
