/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.model;

import org.junit.Test;


/**
 * Model tests for Feed
 */
public class FeedTest {
    private final Feed model = new Feed();

    /**
     * Model tests for Feed
     */
    @Test
    public void testFeed() {
        // TODO: test Feed
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'subtitle'
     */
    @Test
    public void subtitleTest() {
        // TODO: test subtitle
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'entry'
     */
    @Test
    public void entryTest() {
        // TODO: test entry
    }

    /**
     * Test the property 'totalResults'
     */
    @Test
    public void totalResultsTest() {
        // TODO: test totalResults
    }

    /**
     * Test the property 'startIndex'
     */
    @Test
    public void startIndexTest() {
        // TODO: test startIndex
    }

    /**
     * Test the property 'itemsPerPage'
     */
    @Test
    public void itemsPerPageTest() {
        // TODO: test itemsPerPage
    }

}
