/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.model;

import org.junit.Test;


/**
 * Model tests for Link
 */
public class LinkTest {
    private final Link model = new Link();

    /**
     * Model tests for Link
     */
    @Test
    public void testLink() {
        // TODO: test Link
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'rel'
     */
    @Test
    public void relTest() {
        // TODO: test rel
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
