/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.api;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import io.github.nicholasphair.arxiv.model.Feed;
import io.github.nicholasphair.arxiv.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Returns a list of users.
     *
     * Optional extended description in CommonMark or HTML.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiQueryGetTest() throws ApiException, JsonProcessingException {
        String searchQuery = "ti:\"electron thermal conductivity\"";
        List<String> idList = null;
        Integer start = 0;
        Integer maxResults = 10;
        String sortBy = "lastUpdatedDate";
        String sortOrder = "ascending";

        XmlMapper xmlMapper = new XmlMapper();
        //xmlMapper.readValue(result, Feed.class);
        api.getApiClient().setObjectMapper(xmlMapper);
        Feed response = api.apiQueryGet(searchQuery, idList, start, maxResults, sortBy, sortOrder);
        System.out.println(response);
    }
}
