/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Feed
 */
@JsonPropertyOrder({
  Feed.JSON_PROPERTY_TITLE,
  Feed.JSON_PROPERTY_SUBTITLE,
  Feed.JSON_PROPERTY_ID,
  Feed.JSON_PROPERTY_UPDATED,
  Feed.JSON_PROPERTY_LINK,
  Feed.JSON_PROPERTY_ENTRY,
  Feed.JSON_PROPERTY_TOTAL_RESULTS,
  Feed.JSON_PROPERTY_START_INDEX,
  Feed.JSON_PROPERTY_ITEMS_PER_PAGE
})
@JsonTypeName("feed")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-07T22:56:24.153-04:00[America/New_York]")
@XmlRootElement(namespace="http://www.w3.org/2005/Atom", name = "Feed")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(namespace="http://www.w3.org/2005/Atom", localName = "Feed")
public class Feed {
  public static final String JSON_PROPERTY_TITLE = "title";
  @XmlElement(name = "title")
  private String title;

  public static final String JSON_PROPERTY_SUBTITLE = "subtitle";
  @XmlElement(name = "subtitle")
  private String subtitle;

  public static final String JSON_PROPERTY_ID = "id";
  @XmlElement(name = "id")
  private String id;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @XmlElement(name = "updated")
  private String updated;

  public static final String JSON_PROPERTY_LINK = "link";
  @XmlElement(name = "link")
  private Link link;

  public static final String JSON_PROPERTY_ENTRY = "entry";
  // Is a container wrapped=false
  // items.name=entry items.baseName=entry items.xmlName= items.xmlNamespace=
  // items.example= items.type=Myentry
  @XmlElement(name = "entry")
  private List<Myentry> entry = null;

  public static final String JSON_PROPERTY_TOTAL_RESULTS = "totalResults";
  @XmlElement(namespace="http://a9.com/-/spec/opensearch/1.1/", name = "totalResults")
  private String totalResults;

  public static final String JSON_PROPERTY_START_INDEX = "startIndex";
  @XmlElement(namespace="http://a9.com/-/spec/opensearch/1.1/", name = "startIndex")
  private String startIndex;

  public static final String JSON_PROPERTY_ITEMS_PER_PAGE = "itemsPerPage";
  @XmlElement(namespace="http://a9.com/-/spec/opensearch/1.1/", name = "itemsPerPage")
  private String itemsPerPage;

  public Feed() { 
  }

  public Feed title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "title")

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "title")
  public void setTitle(String title) {
    this.title = title;
  }


  public Feed subtitle(String subtitle) {
    
    this.subtitle = subtitle;
    return this;
  }

   /**
   * Get subtitle
   * @return subtitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUBTITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subtitle")

  public String getSubtitle() {
    return subtitle;
  }


  @JsonProperty(JSON_PROPERTY_SUBTITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "subtitle")
  public void setSubtitle(String subtitle) {
    this.subtitle = subtitle;
  }


  public Feed id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")
  public void setId(String id) {
    this.id = id;
  }


  public Feed updated(String updated) {
    
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "updated")

  public String getUpdated() {
    return updated;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "updated")
  public void setUpdated(String updated) {
    this.updated = updated;
  }


  public Feed link(Link link) {
    
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "link")

  public Link getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "link")
  public void setLink(Link link) {
    this.link = link;
  }


  public Feed entry(List<Myentry> entry) {
    
    this.entry = entry;
    return this;
  }

  public Feed addEntryItem(Myentry entryItem) {
    if (this.entry == null) {
      this.entry = new ArrayList<>();
    }
    this.entry.add(entryItem);
    return this;
  }

   /**
   * Get entry
   * @return entry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlElementWrapper(useWrapping=false)
  public List<Myentry> getEntry() {
    return entry;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntry(List<Myentry> entry) {
    this.entry = entry;
  }


  public Feed totalResults(String totalResults) {
    
    this.totalResults = totalResults;
    return this;
  }

   /**
   * Get totalResults
   * @return totalResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOTAL_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "totalResults")

  public String getTotalResults() {
    return totalResults;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "totalResults")
  public void setTotalResults(String totalResults) {
    this.totalResults = totalResults;
  }


  public Feed startIndex(String startIndex) {
    
    this.startIndex = startIndex;
    return this;
  }

   /**
   * Get startIndex
   * @return startIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "startIndex")

  public String getStartIndex() {
    return startIndex;
  }


  @JsonProperty(JSON_PROPERTY_START_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "startIndex")
  public void setStartIndex(String startIndex) {
    this.startIndex = startIndex;
  }


  public Feed itemsPerPage(String itemsPerPage) {
    
    this.itemsPerPage = itemsPerPage;
    return this;
  }

   /**
   * Get itemsPerPage
   * @return itemsPerPage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ITEMS_PER_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "itemsPerPage")

  public String getItemsPerPage() {
    return itemsPerPage;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS_PER_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://a9.com/-/spec/opensearch/1.1/", localName = "itemsPerPage")
  public void setItemsPerPage(String itemsPerPage) {
    this.itemsPerPage = itemsPerPage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feed feed = (Feed) o;
    return Objects.equals(this.title, feed.title) &&
        Objects.equals(this.subtitle, feed.subtitle) &&
        Objects.equals(this.id, feed.id) &&
        Objects.equals(this.updated, feed.updated) &&
        Objects.equals(this.link, feed.link) &&
        Objects.equals(this.entry, feed.entry) &&
        Objects.equals(this.totalResults, feed.totalResults) &&
        Objects.equals(this.startIndex, feed.startIndex) &&
        Objects.equals(this.itemsPerPage, feed.itemsPerPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, subtitle, id, updated, link, entry, totalResults, startIndex, itemsPerPage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feed {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    subtitle: ").append(toIndentedString(subtitle)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("    itemsPerPage: ").append(toIndentedString(itemsPerPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

