/*
 * arXiv API
 * Specification of the api described in [arXiv documentation](https://arxiv.org/help/api/user-manua).
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.nicholasphair.arxiv.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import javax.xml.bind.annotation.*;

/**
 * Myentry
 */
@JsonPropertyOrder({
  Myentry.JSON_PROPERTY_TITLE,
  Myentry.JSON_PROPERTY_ID,
  Myentry.JSON_PROPERTY_PUBLISHED,
  Myentry.JSON_PROPERTY_UPDATED,
  Myentry.JSON_PROPERTY_SUMMARY,
  Myentry.JSON_PROPERTY_AUTHOR,
  Myentry.JSON_PROPERTY_LINK,
  Myentry.JSON_PROPERTY_DOI,
  Myentry.JSON_PROPERTY_COMMENT,
  Myentry.JSON_PROPERTY_JOURNAL_REF,
  Myentry.JSON_PROPERTY_PRIMARY_CATEGORY,
  Myentry.JSON_PROPERTY_CATEGORY
})
@JsonTypeName("myentry")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-07T22:56:24.153-04:00[America/New_York]")
@XmlRootElement(name = "Myentry")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "Myentry")
public class Myentry {
  public static final String JSON_PROPERTY_TITLE = "title";
  @XmlElement(name = "title")
  private String title;

  public static final String JSON_PROPERTY_ID = "id";
  @XmlElement(name = "id")
  private String id;

  public static final String JSON_PROPERTY_PUBLISHED = "published";
  @XmlElement(name = "published")
  private String published;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @XmlElement(name = "updated")
  private String updated;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @XmlElement(name = "summary")
  private String summary;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  // Is a container wrapped=false
  // items.name=author items.baseName=author items.xmlName= items.xmlNamespace=
  // items.example= items.type=Author
  @XmlElement(name = "author")
  private List<Author> author = null;

  public static final String JSON_PROPERTY_LINK = "link";
  // Is a container wrapped=false
  // items.name=link items.baseName=link items.xmlName= items.xmlNamespace=
  // items.example= items.type=Link
  @XmlElement(name = "link")
  private List<Link> link = null;

  public static final String JSON_PROPERTY_DOI = "doi";
  @XmlElement(namespace="http://arxiv.org/schemas/atom", name = "doi")
  private String doi;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @XmlElement(namespace="http://arxiv.org/schemas/atom", name = "comment")
  private String comment;

  public static final String JSON_PROPERTY_JOURNAL_REF = "journal_ref";
  @XmlElement(namespace="http://arxiv.org/schemas/atom", name = "journal_ref")
  private String journalRef;

  public static final String JSON_PROPERTY_PRIMARY_CATEGORY = "primary_category";
  @XmlElement(name = "primary_category")
  private MyentryPrimaryCategory primaryCategory;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  // Is a container wrapped=false
  // items.name=category items.baseName=category items.xmlName= items.xmlNamespace=
  // items.example= items.type=Category
  @XmlElement(name = "category")
  private List<Category> category = null;

  public Myentry() { 
  }

  public Myentry title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "title")

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "title")
  public void setTitle(String title) {
    this.title = title;
  }


  public Myentry id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "id")
  public void setId(String id) {
    this.id = id;
  }


  public Myentry published(String published) {
    
    this.published = published;
    return this;
  }

   /**
   * Get published
   * @return published
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "published")

  public String getPublished() {
    return published;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "published")
  public void setPublished(String published) {
    this.published = published;
  }


  public Myentry updated(String updated) {
    
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "updated")

  public String getUpdated() {
    return updated;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "updated")
  public void setUpdated(String updated) {
    this.updated = updated;
  }


  public Myentry summary(String summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "summary")

  public String getSummary() {
    return summary;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "summary")
  public void setSummary(String summary) {
    this.summary = summary;
  }


  public Myentry author(List<Author> author) {
    
    this.author = author;
    return this;
  }

  public Myentry addAuthorItem(Author authorItem) {
    if (this.author == null) {
      this.author = new ArrayList<>();
    }
    this.author.add(authorItem);
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlElementWrapper(useWrapping=false)
  public List<Author> getAuthor() {
    return author;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(List<Author> author) {
    this.author = author;
  }


  public Myentry link(List<Link> link) {
    
    this.link = link;
    return this;
  }

  public Myentry addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<>();
    }
    this.link.add(linkItem);
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlElementWrapper(useWrapping=false)

  public List<Link> getLink() {
    return link;
  }


  @JsonProperty(JSON_PROPERTY_LINK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLink(List<Link> link) {
    this.link = link;
  }


  public Myentry doi(String doi) {
    
    this.doi = doi;
    return this;
  }

   /**
   * Get doi
   * @return doi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "doi")

  public String getDoi() {
    return doi;
  }


  @JsonProperty(JSON_PROPERTY_DOI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "doi")
  public void setDoi(String doi) {
    this.doi = doi;
  }


  public Myentry comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "comment")

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "comment")
  public void setComment(String comment) {
    this.comment = comment;
  }


  public Myentry journalRef(String journalRef) {
    
    this.journalRef = journalRef;
    return this;
  }

   /**
   * Get journalRef
   * @return journalRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JOURNAL_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "journal_ref")

  public String getJournalRef() {
    return journalRef;
  }


  @JsonProperty(JSON_PROPERTY_JOURNAL_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(namespace="http://arxiv.org/schemas/atom", localName = "journal_ref")
  public void setJournalRef(String journalRef) {
    this.journalRef = journalRef;
  }


  public Myentry primaryCategory(MyentryPrimaryCategory primaryCategory) {
    
    this.primaryCategory = primaryCategory;
    return this;
  }

   /**
   * Get primaryCategory
   * @return primaryCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRIMARY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "primary_category")

  public MyentryPrimaryCategory getPrimaryCategory() {
    return primaryCategory;
  }


  @JsonProperty(JSON_PROPERTY_PRIMARY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlProperty(localName = "primary_category")
  public void setPrimaryCategory(MyentryPrimaryCategory primaryCategory) {
    this.primaryCategory = primaryCategory;
  }


  public Myentry category(List<Category> category) {
    
    this.category = category;
    return this;
  }

  public Myentry addCategoryItem(Category categoryItem) {
    if (this.category == null) {
      this.category = new ArrayList<>();
    }
    this.category.add(categoryItem);
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JacksonXmlElementWrapper(useWrapping=false)

  public List<Category> getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(List<Category> category) {
    this.category = category;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Myentry myentry = (Myentry) o;
    return Objects.equals(this.title, myentry.title) &&
        Objects.equals(this.id, myentry.id) &&
        Objects.equals(this.published, myentry.published) &&
        Objects.equals(this.updated, myentry.updated) &&
        Objects.equals(this.summary, myentry.summary) &&
        Objects.equals(this.author, myentry.author) &&
        Objects.equals(this.link, myentry.link) &&
        Objects.equals(this.doi, myentry.doi) &&
        Objects.equals(this.comment, myentry.comment) &&
        Objects.equals(this.journalRef, myentry.journalRef) &&
        Objects.equals(this.primaryCategory, myentry.primaryCategory) &&
        Objects.equals(this.category, myentry.category);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, id, published, updated, summary, author, link, doi, comment, journalRef, primaryCategory, category);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Myentry {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    doi: ").append(toIndentedString(doi)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    journalRef: ").append(toIndentedString(journalRef)).append("\n");
    sb.append("    primaryCategory: ").append(toIndentedString(primaryCategory)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

